server:
  port: 8080

spring:
  application:
    name: smart-queue-system

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    mongodb:
      uri: ${MONGO_URI}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

app:
  jwt:
    secret: smartQueueJwtSecretKey2024ProductionReadySystemByDeveloper
    expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html